name: NASA TT CI
# define triggers to do workflow
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
# each project need jobs to test
jobs:
  # testing when building
  build:
    # lists of enviroment this job can run
    env:
      CI: true
      MONGO_URL: mongodb://localhost/node_nasa
    strategy:
      matrix:
        node-version: [20.x, 22.x]
        mongodb-version: ["8.0"]
    runs-on: ubuntu-latest
    # define different actions at ubuntu to do for testing
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      # to connect MongoDB on workflow
      - name: Use MongoDB from GitHub actions
        uses: supercharge/mongodb-github-action@1.12.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - run: npm install
        # run build on client code
      - run: npm run build --prefix client
      - run: npm test
